import ThemeCodeBlock from "../types/ThemeCodeBlock";

const DarkTheme: ThemeCodeBlock = {
    lineNumberColor: "",
    lineNumberBgColor: "",
    backgroundColor: "",
    textColor: "",
    substringColor: "",
    keywordColor: "",
    attributeColor: "",
    selectorAttributeColor: "",
    docTagColor: "",
    nameColor: "",
    builtInColor: "",
    literalColor: "",
    bulletColor: "",
    codeColor: "",
    additionColor: undefined,
    regexpColor: "",
    symbolColor: "",
    variableColor: "",
    templateVariableColor: "",
    linkColor: "",
    selectorClassColor: "",
    typeColor: "",
    stringColor: "",
    selectorIdColor: "",
    quoteColor: "",
    templateTagColor: "",
    deletionColor: undefined,
    titleColor: "",
    sectionColor: "",
    commentColor: "",
    metaKeywordColor: "",
    metaColor: "",
    functionColor: "",
    numberColor: "",
};

export default DarkTheme;